---
- hosts: all
  become: yes
  tasks:

# -----------------------------------------------------------------------------
# User setup
# -----------------------------------------------------------------------------

    - name: add user 'admin'
      user: 
        name: admin
        groups: adm,sudo
        shell: /bin/bash
        state: present
        password:
            $6$rounds=656000$2jNVVCliDs5XvmZs$eZ4F0WO6d6w5cBoMZ341hbuknOjx3ObhPHcgSR0D76gICz/Cc9IzXcPGaWzMdpiT7Cp.sflfiPhRDROvNH0eF/
# -----------------------------------------------------------------------------
# Interfaces setup
# -----------------------------------------------------------------------------

    - name: copy interface file for restart
      copy: src=interfaces dest=/etc/network/interfaces

# -----------------------------------------------------------------------------
# Reboot system for clean start; 
# removes the Vagrant stuff in /etc/network/interfaces
# -----------------------------------------------------------------------------

    - name: reboot system ...
      command: /sbin/reboot
      ignore_errors: yes
